import { Inter } from "next/font/google";
import '../styles/globals.css'
import Navbar from "../components/Navbar";
import { ReactNode } from 'react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="bg-background text-foreground min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
